apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  containerConcurrency: 5
  template:
    spec:
      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName }}
      {{- end }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        env:
        - name: RUST_LOG
          value: wasi::api
        lifecycle:
          preStop:
            httpGet:
              port: 8081
