apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      runtimeClassName: crun
      containers:
      - image: {{ .Values.image }}
